### ISSUE TITLE
Test Lineage 20.0 release

### ISSUE THREAD

**Issue by MehediHasannOvi** [fakemanoan/LineageOS-Releases#39]
google service ar not working , playstor Crashe

**Comment by hamzamaqsood877** [comment]
Did you updated Gapps to Android 13? When you upgrade rom you must reflash gapps version to the newer version.. Try nikgapps package. I'm uaing test build and google apps are working perfectly fine.

**Comment by fakemanoan** [comment]
You must do a clean install when going from 12 -> 13 test builds. You also need an android 13 version of gapps. Need more details of your install process or I cant help

> Animations are a bit laggy especially when you pull down the notification bar. The fingerprint scanner works slowly. Videos on Instagram have poor quality.

It is likely that instagram videos have poor quality due to hardware video decoding being broken currently for AVC, so it defaults back to lower quality software decoding.

**Comment by bugraahmet** [comment]
In-calls, sometimes for a couple of seconds, I can't hear anything, but after that, I am able to communicate, and also Bluetooth audio doesn't work in calls.

**Comment by MehediHasannOvi** [comment]
sim not show imei also not show .. when i use 19-20230214 sim working but call ar voice ar not working , also sim are not working on android 13

**Comment by hamzamaqsood877** [comment]
> sim not show imei also not show .. when i use 19-20230214 sim working but call ar voice ar not working , also sim are not working on android 13

Earlier asked you about log or baseband or like a screenshot from settings..  And did you take any backup from twrp before?
