### ISSUE TITLE
possible to get VoLTE working on the S6?

### ISSUE THREAD

**Issue by AntiSol** [fakemanoan/LineageOS-Releases#91]
Hi, sorry this isn't really an issue, more of a question: I was looking in your FAQ and it says:

`Samsung uses a proprietary IMS that is hard to get working in Lineage, so currently doesn’t work`

I've been notified that the 3G network here in AU will be shutting down and that I need to upgrade to get VoLTE to continue using my SM-G920F (currently running an old lineageos build) after that.

You say it's "hard" to get working on lineage - how hard? Is it that the open source IMS implementation doesn't exist? doesn't work well? Something else? Or is this more of a licensing thing, i.e it's relatively straightforward to copy the proprietary IMS bit, but not legal or not FOSS?

(I'm not very into phones and I'm not sure I understand the issue completely, apologies if this is a dumb question or if there's a better place to be asking this)

I'm faced with the prospect of being forced to buy new hardware to replace something that is perfectly functional, which I find  extremely distasteful. Any help you can provide would be massively appreciated :)

thanks for your time

**Comment by fakemanoan** [comment]
Hi
It is sadly common in many parts of the world right now that 2G/3G networks will be shut down, and as a result _all_ Samsung devices running custom AOSP based ROMs will cease to work for calling.

This has been a problem for as long as Samsung devices have been on AOSP based ROMs, like Lineage. Samsung uses a custom/proprietary IMS that is tied to and integrated with the stock OS, which is hard to reverse into AOSP. No one has gotten a fully working implementation in 10+ years because of the difficulty.

Recently there have been some efforts to attempt to get something working, but are limited to a specific device or only have certain functions working. 

See:
https://xdaforums.com/t/research-wip-possible-volte-enablement-for-samsung-devices-on-aosp-based-roms.4664947/
https://github.com/phhusson/ims

Because they are purely experimental, I wont put them into my ROMs I build.

Currently the only way to get VoLTE/VoWiFi working on Samsung devices is to use a Samsung based ROM. This means your options are limited to either stock firmware, Android 8 ports (like ultimate oreo, A8 ports, etc) or Android 9 ports (FloydROM). In my experience Android 8 ports are the most stable while providing a slightly newer OS.

If you want to get VoLTE on the S6 (and consequently other Samsung devices) support the 2 projects I linked to previously! 

One day maybe VoLTE will work but sadly for now this is a "nofix".

**Comment by AntiSol** [comment]
thank you very much for your detailed reply! Yes I had noticed that IMS is listed as a "quirk" even for the latest samsung devices. I'll certainly look at the projects you've linked to. Thanks again!
